"""Train the ROI regression model on the synthetic campaigns dataset.

Run from the ml-service directory:

    python -m app.train_roi

Inputs
------
    ml-service/data/synthetic_campaigns.csv
        Generated by ``scripts/generate_dataset.py``. If the file is missing,
        training aborts with a helpful error instead of re-inventing data
        silently.

Outputs
-------
    ml-service/models/roi_model.joblib
        A dict with keys:
            - pipeline :  sklearn Pipeline (preprocessing + regressor)
            - targets  :  list[str]  (order of the regressor's output columns)
            - metrics  :  dict       (MAE / RMSE / R2 per target, on holdout)

    ml-service/models/roi_model.metrics.json
        Human-readable copy of the metrics, useful for the FYP report.

Design choices (kept deliberately simple)
-----------------------------------------
* **Algorithm**: GradientBoostingRegressor. A tree ensemble is a good match
  for our mix of numeric + one-hot-encoded categorical features and handles
  non-linear effects (quadratic peak in posting_hour, holiday lift, etc.)
  without feature engineering.
* **Multi-output**: we predict two correlated targets -- ``engagement_rate``
  and ``roi`` -- by wrapping the base regressor in
  ``MultiOutputRegressor``. This fits one model per target. It's the
  least-surprising choice for an MVP; we can switch to a native multi-output
  model later if the targets need to share structure.
* **Preprocessing**: ``ColumnTransformer`` with ``OneHotEncoder`` for the
  three categorical columns and pass-through for the numerics.
  ``handle_unknown="ignore"`` means an inference-time category we didn't see
  during training simply contributes zero to the one-hot vector rather than
  crashing.
* **Evaluation**: a standard 80/20 holdout with a fixed random_state.
  Reporting MAE, RMSE, and R2 per target is enough for a prototype; a real
  deployment would use K-fold CV and confidence intervals.
"""

from __future__ import annotations

import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputRegressor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

from app.preprocess import CATEGORICAL_FEATURES, NUMERIC_FEATURES


ML_ROOT = Path(__file__).resolve().parent.parent
DATA_PATH = ML_ROOT / "data" / "synthetic_campaigns.csv"
MODEL_DIR = ML_ROOT / "models"
MODEL_PATH = MODEL_DIR / "roi_model.joblib"
METRICS_PATH = MODEL_DIR / "roi_model.metrics.json"

# Ordered list -- the pipeline's predict() returns an array whose columns
# follow this same order. roi_model.py relies on that.
TARGETS = ["engagement_rate", "roi"]


def _build_pipeline() -> Pipeline:
    """Preprocessing + GradientBoosting ensemble, one regressor per target."""
    preprocess = ColumnTransformer(
        transformers=[
            ("cat", OneHotEncoder(handle_unknown="ignore"), CATEGORICAL_FEATURES),
            ("num", "passthrough", NUMERIC_FEATURES),
        ]
    )
    # Conservative hyperparameters: shallow trees + low learning rate. More
    # trees would overfit the ~800-row synthetic set with no real upside.
    base_regressor = GradientBoostingRegressor(
        n_estimators=300,
        max_depth=3,
        learning_rate=0.05,
        random_state=42,
    )
    return Pipeline(
        steps=[
            ("pre", preprocess),
            ("model", MultiOutputRegressor(base_regressor)),
        ]
    )


def _compute_metrics(y_true: pd.DataFrame, y_pred: np.ndarray) -> dict:
    metrics: dict = {}
    for i, target in enumerate(TARGETS):
        actual = y_true[target].to_numpy()
        predicted = y_pred[:, i]
        metrics[target] = {
            "mae": float(mean_absolute_error(actual, predicted)),
            "rmse": float(np.sqrt(np.mean((actual - predicted) ** 2))),
            "r2": float(r2_score(actual, predicted)),
        }
    return metrics


def main() -> None:
    if not DATA_PATH.exists():
        raise SystemExit(
            f"Dataset not found at {DATA_PATH}.\n"
            f"Generate it first:  python scripts/generate_dataset.py"
        )

    df = pd.read_csv(DATA_PATH)

    missing_features = [c for c in CATEGORICAL_FEATURES + NUMERIC_FEATURES if c not in df.columns]
    missing_targets = [t for t in TARGETS if t not in df.columns]
    if missing_features or missing_targets:
        raise SystemExit(
            f"CSV is missing required columns. "
            f"Features missing: {missing_features}. Targets missing: {missing_targets}."
        )

    X = df[CATEGORICAL_FEATURES + NUMERIC_FEATURES]
    y = df[TARGETS]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    pipe = _build_pipeline()
    pipe.fit(X_train, y_train)

    y_pred = pipe.predict(X_test)
    metrics = _compute_metrics(y_test, y_pred)
    metrics["n_train"] = int(len(X_train))
    metrics["n_test"] = int(len(X_test))

    MODEL_DIR.mkdir(parents=True, exist_ok=True)
    joblib.dump(
        {"pipeline": pipe, "targets": TARGETS, "metrics": metrics},
        MODEL_PATH,
    )
    METRICS_PATH.write_text(json.dumps(metrics, indent=2))

    print(f"Saved model to {MODEL_PATH}")
    print(f"Metrics:\n{json.dumps(metrics, indent=2)}")


if __name__ == "__main__":
    main()
